/** Auto-generated by scripts/build-srd-entities.mjs — unclassified or skipped index rows. */
import type { SrdOrphanRecord } from "./types";

export const SRD_ORPHAN_COUNT = 0;

export const SRD_ORPHANS: readonly SrdOrphanRecord[] = [] as const;
